### ISSUE TITLE
Still Up to Date?

### ISSUE THREAD

**Issue by AkaKuro4Ever** [torchbox/vagrant-django-template#20]
Hi there, it's been a while since this project has been updated, so I wanted to ask if this is still the canonical template to develop django/vagrant projects, or if there are new templates Torchbox have made after this one (and the vagrant-django-base project as well)

**Comment by gasman** [comment]
Hi @AkaKuro4Ever,
We don't currently have an up-to-date template for vanilla Django projects. Since the majority of our new projects are Wagtail sites, it's more time-effective for us to maintain an in-house Wagtail template (which is non-public, unfortunately) and manually remove the Wagtail-specific code for the occasional non-Wagtail projects.
